### ISSUE TITLE
Not all words are matched #2

### ISSUE THREAD

**Issue by maxtepkeev** [abusix/ahocorapy#3]
Hi @FrederikP 

First of all thanks for the fix in issue #1 , I can confirm that it solved the problem we had.

Unfortunately we're still experiencing issues with matching and here's another use case to reproduce the bug:

```python
text = '/foo/bar'
words = ['foo/', 'foo', '/foo/', '/bar']
tree = KeywordTree(case_insensitive=True)
for word in words:
    tree.add(word)
tree.finalize()
print set([word for word, position in tree.search_all(text)])
```

Expected result: ``set(['foo', '/foo/', 'foo/', '/bar']))``
Actual result ``set(['foo', '/foo/', 'foo/'])``

Hopefully that will be the last one :)

Thanks in advance.

**Comment by FrederikP** [comment]
Hi @maxtepkeev,
thanks for reporting another one!

I can confirm, that this is easily reproduce-able.
I'll work on a fix.

**Comment by FrederikP** [comment]
@maxtepkeev please retry with version 1.4.2
Looking forward to your feedback.

**Comment by maxtepkeev** [comment]
Hi @FrederikP 

I've just tested and it works perfectly. I don't see any more problems with our data, so we can finally add this great library to production. Thanks!

P.S. It would be great to have a changelog to see what has changed since the last version

**Comment by FrederikP** [comment]
Glad to hear that.
I added a [changelog](https://github.com/abusix/ahocorapy/blob/master/CHANGELOG) starting with version 1.1.0, because most changes before that are a long time ago and are not really significant to the current version anymore. If anyone wants more insights, I can only point to the git history.

Again, if you have any more issues or ideas for this library, don't hesitate to open up another issue.

**Comment by maxtepkeev** [comment]
That's awesome! Thanks!
